apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- users-seed-job.yaml
- accounts-seed-job.yaml
- transactions-seed-job.yaml
- notifications-seed-job.yaml

namespace: mako-services

commonLabels:
  app.kubernetes.io/name: mako-data-seeds
  app.kubernetes.io/component: data-initialization
  app.kubernetes.io/part-of: mako-bank
