apiVersion: batch/v1
kind: Job
metadata:
  name: users-db-seed
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: seed-users-db
        image: postgres:16
        env:
        - name: PGHOST
          value: "postgres-users-postgresql.mako-services.svc.cluster.local"
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: "mako_users"
        - name: PGUSER
          value: "bank"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-users-secret
              key: password
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h $PGHOST -p $PGPORT -U $PGUSER; do
            echo "PostgreSQL is not ready yet. Waiting..."
            sleep 5
          done
          
          echo "PostgreSQL is ready. Starting data seeding..."
          
          # Execute the seed SQL
          psql -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE << 'EOF'
          -- Users seed data
          CREATE TABLE IF NOT EXISTS USERS
          (
              ID           VARCHAR(36) PRIMARY KEY NOT NULL,
              USER_NAME    VARCHAR(255)            NOT NULL,
              KEYCLOAK_ID  VARCHAR(255) UNIQUE     NOT NULL,
              FIRST_NAME   VARCHAR(255)            NOT NULL,
              LAST_NAME    VARCHAR(255)            NOT NULL,
              ADDRESS      VARCHAR(255)            NOT NULL,
              EMAIL        VARCHAR(255) UNIQUE     NOT NULL,
              PHONE_NUMBER VARCHAR(20)             NOT NULL
          );

          -- Insert sample users
          INSERT INTO USERS (ID, USER_NAME, KEYCLOAK_ID, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES
          ('user-001', 'john', 'cdd4e82f-1ceb-4600-908f-f435df3672bd', 'John', 'Walter', '123 Main St, New York, NY 10001', 'john.walter@email.com', '+1-555-0101'),
          ('user-002', 'jane', 'a5ebbd33-0ef4-4203-abe1-fddc35762b04', 'Jane', 'Smith', '456 Oak Ave, Los Angeles, CA 90210', 'jane.smith@email.com', '+1-555-0102'),
          ('user-003', 'bob', '0edfcbff-b61a-4530-9618-c9f309594b29', 'Bob', 'Johnson', '789 Pine Rd, Chicago, IL 60601', 'bob.johnson@email.com', '+1-555-0103')
          ON CONFLICT (ID) DO NOTHING;
          
          EOF
          
          echo "Users database seeding completed successfully!"
      backoffLimit: 3
