apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-users
  template:
    metadata:
      labels:
        app: mako-users
    spec:
      containers:
        - name: mako-users
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-users:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "200Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.argocd.svc.cluster.local:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudsql-proxy.argocd.svc.cluster.local:5432/mako_bank?currentSchema=users"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.argocd.svc.cluster.local:9092"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-master.argocd.svc.cluster.local"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              value: "redispw"
