apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-users
  template:
    metadata:
      labels:
        app: mako-users
    spec:
      containers:
        - name: mako-users
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-users:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"
