apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- nginx-config.yaml
- ingress-gcp.yaml

images:
- name: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-users-web
  newName: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-users-web
  newTag: placeholder
