apiVersion: v1
kind: Service
metadata:
  name: mako-users-web
  annotations:
    cloud.google.com/backend-config: '{"default": "mako-users-web-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 4204
      targetPort: 4204
      protocol: TCP
      name: http
  selector:
    app: mako-users-web
