apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "mako-ingress-ip-global"
    networking.gke.io/managed-certificates: "argocd-ssl-cert"
    networking.gke.io/v1beta1.FrontendConfig: "argocd-http-to-https"
    cloud.google.com/backend-config: '{"default": "argocd-backend-config"}'
spec:
  rules:
    - host: argocd.mako-bank.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
