apiVersion: v1
kind: Service
metadata:
  name: mako-accounts-web
spec:
  type: ClusterIP
  ports:
    - port: 4202
      targetPort: 4202
      protocol: TCP
      name: http
  selector:
    app: mako-accounts-web
