kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions-web=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions-web:a4ea587ffe19f4c9e5a3d12faa3663269bfa1e73
