apiVersion: v1
kind: Service
metadata:
  name: mako-transactions-web
spec:
  type: ClusterIP
  ports:
    - port: 4203
      targetPort: 4203
      protocol: TCP
      name: http
  selector:
    app: mako-transactions-web
