kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-notifications=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-notifications:0953b322bc966f763cccff4794e9c839950e42b5
