apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-notifications
  template:
    metadata:
      labels:
        app: mako-notifications
    spec:
      containers:
        - name: mako-notifications
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-notifications:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "64Mi"        # Reduced from 128Mi
              cpu: "25m"            # Reduced from 50m
              ephemeral-storage: "100Mi"  # Reduced from 200Mi
            limits:
              memory: "128Mi"       # Reduced from 256Mi
              cpu: "100m"           # Reduced from 200m
              ephemeral-storage: "200Mi"  # Reduced from 500Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"
            # Remove direct service calls - use API Gateway instead
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudsql-proxy.mako-db.svc.cluster.local:5432/mako_bank?currentSchema=notifications"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
