apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-notifications
  template:
    metadata:
      labels:
        app: mako-notifications
    spec:
      containers:
        - name: mako-notifications
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-notifications:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"
            - name: SERVICES_ACCOUNTS_URL
              value: "http://mako-accounts.mako-services.svc.cluster.local:8083/accounts"
            - name: SERVICES_USERS_URL
              value: "http://mako-users.mako-services.svc.cluster.local:8082/users"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-notifications-postgresql.mako-notifications.svc.cluster.local:5432/mako_notifications"
            - name: SPRING_DATASOURCE_USERNAME
              value: "bank"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "bankpw"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
