apiVersion: v1
kind: Service
metadata:
  name: mako-notifications
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: mako-notifications
