kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-service-registry=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-service-registry:34ac23b46d75982bf718eb90598e40517105c041
