apiVersion: v1
kind: Service
metadata:
  name: mako-service-registry
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: mako-service-registry
