# Placeholder values. All real values will be provided by the ArgoCD Application manifest.
name: "placeholder-name"
replicaCount: 1
image:
  repository: "placeholder-repo"
  tag: "placeholder-tag"
  pullPolicy: IfNotPresent
service:
  port: 8080
env:
  - name: EXAMPLE
    value: "example"