apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-shell-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /
    port: 4200
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
