apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-shell-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 4200
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30
