apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mako-frontend-shell
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "mako-bank-ssl-cert"
    kubernetes.io/ingress.allow-http: "true"  # Allow HTTP during cert provisioning
spec:
  tls:
    - hosts:
        - mako-bank.com
      secretName: ""  # Empty for Google-managed certificates
  rules:
    - host: mako-bank.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mako-shell
                port:
                  name: http
