apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-dashboard-web-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 4201
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-accounts-web-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 4202
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-transactions-web-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 4203
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-users-web-backend-config
  namespace: mako-frontend
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    port: 4204
  timeoutSec: 60
  connectionDraining:
    drainingTimeoutSec: 30
