apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mako-dashboard-web-gcp
  annotations:
    # Use Google Cloud Load Balancer instead of nginx
    kubernetes.io/ingress.class: "gce"
    
    # Enable Google-managed SSL certificates
    kubernetes.io/ingress.global-static-ip-name: "mako-bank-ip"
    networking.gke.io/managed-certificates: "mako-bank-ssl-cert"
    
    # Optional: Configure SSL redirect
    kubernetes.io/ingress.allow-http: "false"
    
    # Optional: Configure backend timeout
    cloud.google.com/backend-config: '{"default": "mako-backend-config"}'
spec:
  rules:
    - host: dashboard.mako-bank.com  # Use real domain instead of .local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mako-dashboard-web
                port:
                  name: http
  tls:
    - hosts:
      - dashboard.mako-bank.com
      secretName: mako-bank-tls
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: mako-bank-ssl-cert
spec:
  domains:
    - dashboard.mako-bank.com
    - api.mako-bank.com
    - argocd.mako-bank.com
    - users.mako-bank.com
    - accounts.mako-bank.com
    - transactions.mako-bank.com
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mako-backend-config
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 10
    port: 8080
    type: HTTP
    requestPath: /health
