apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mako-api-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/2-services/mako-api-gateway
    repoURL: https://github.com/MakowiecJ/mako-k8s-config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: mako-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true