apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mako-api-gateway
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mako-api-gateway=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway
    argocd-image-updater.argoproj.io/mako-api-gateway.kustomize.image-name: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway
    argocd-image-updater.argoproj.io/mako-api-gateway.update-strategy: latest
    argocd-image-updater.argoproj.io/mako-api-gateway.allow-tags: regexp:^.*
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: apps/2-services/mako-api-gateway
    repoURL: git@github.com:MakowiecJ/mako-k8s-config.git
    targetRevision: HEAD
    kustomize:
      images:
      - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: mako-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true