apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mako-transactions
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mako-transactions=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions
    argocd-image-updater.argoproj.io/mako-transactions.kustomize.image-name: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions
    argocd-image-updater.argoproj.io/mako-transactions.update-strategy: latest
    argocd-image-updater.argoproj.io/mako-transactions.allow-tags: regexp:^.*
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-git-creds
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kustomize/mako-transactions
    repoURL: git@github.com:MakowiecJ/mako-k8s-config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
