apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudsql-proxy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: kustomize/cloudsql-proxy
    repoURL: git@github.com:MakowiecJ/mako-k8s-config.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: mako-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
