apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 22.1.5
    helm:
      values: |
        zookeeper:
          persistence:
            enabled: true
            size: 1Gi
        controller:
          persistence:
            enabled: true
            size: 1Gi
        broker:
          persistence:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    