apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MakowiecJ/mako-k8s-config.git
    targetRevision: HEAD
    path: kustomize/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
