apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-users
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.12.10
    helm:
      values: |
        auth:
          database: mako_users
          username: bank
          password: "bankpw"
        primary:
          persistence:
            enabled: true
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mako-users
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true