# Resource Quotas for namespaces to prevent resource starvation
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mako-services-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "500m"      # Reduced from 2
    requests.memory: 1Gi      # Reduced from 4Gi
    limits.cpu: "1"           # Reduced from 4
    limits.memory: 2Gi        # Reduced from 8Gi
    pods: "10"                # Reduced from 20
    persistentvolumeclaims: "5"  # Reduced from 10
    services: "8"             # Reduced from 15

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mako-frontend-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "100m"      # Reduced from 500m - single consolidated pod
    requests.memory: 128Mi    # Reduced from 1Gi
    limits.cpu: "300m"        # Reduced from 1
    limits.memory: 256Mi      # Reduced from 2Gi
    pods: "3"                 # Reduced from 10 - only 1 pod needed
    services: "3"             # Reduced from 8

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: keycloak-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "5"
    persistentvolumeclaims: "5"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
    persistentvolumeclaims: "10"
