kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway:fd9a885364c470995955f4739398650db833b9eb
