apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-api-gateway
  template:
    metadata:
      labels:
        app: mako-api-gateway
    spec:
      containers:
        - name: mako-api-gateway
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway:e28556cc5ddd8fb5b3d6bc01521f5421b936a602"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"