apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-api-gateway
  template:
    metadata:
      labels:
        app: mako-api-gateway
    spec:
      containers:
        - name: mako-api-gateway
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-api-gateway:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
              ephemeral-storage: "200Mi"
            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"
            - name: KEYCLOAK_REALM_URL
              value: "http://keycloak.keycloak.svc.cluster.local:8080"