apiVersion: v1
kind: Service
metadata:
  name: mako-api-gateway
  annotations:
    cloud.google.com/backend-config: '{"default": "mako-api-gateway-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: mako-api-gateway