kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-transactions:c45b7a2a5fc8ef1245c5a86ebc739b32dacad033
