apiVersion: v1
kind: Service
metadata:
  name: mako-transactions
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: mako-transactions
