apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-shell
  template:
    metadata:
      labels:
        app: mako-shell
    spec:
      containers:
        - name: mako-shell
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-shell:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_PATH
              value: "http://shell.mako-bank.com"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: mako-shell-nginx-config
