apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- nginx-config.yaml
- network-policy.yaml
- ../mako-frontend/backend-config.yaml

images:
- name: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-shell
  newName: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-shell
  newTag: placeholder
