apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mako-shell-network-policy
spec:
  podSelector:
    matchLabels:
      app: mako-shell
  policyTypes:
  - Ingress  
  - Egress
  ingress:
  - from: []  # Allow ingress from GCE load balancer
    ports:
    - protocol: TCP
      port: 4200
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: mako-services
    ports:
    - protocol: TCP
      port: 8081  # API Gateway port
  - to: []  # Allow DNS resolution
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []  # Allow HTTPS for external dependencies
    ports:
    - protocol: TCP
      port: 443
