apiVersion: v1
kind: ConfigMap
metadata:
  name: mako-shell-nginx-config
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       4200;
            server_name  localhost;
            root   /usr/share/nginx/html;
            index  index.html index.htm;

            # CORS headers for Module Federation
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';

            # Handle Angular routing
            location / {
                try_files $uri $uri/ /index.html;
            }

            # Proxy API calls to the backend - FIXED FOR KUBERNETES
            location /api/ {
                proxy_pass http://mako-api-gateway.mako-services.svc.cluster.local:8081/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Enable gzip compression
            gzip on;
            gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }
