apiVersion: v1
kind: Service
metadata:
  name: mako-shell
  annotations:
    cloud.google.com/backend-config: '{"default": "mako-shell-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
      protocol: TCP
      name: http
  selector:
    app: mako-shell
