kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts:d45d69aae921aede58a9dc74b51c3ea0a9ef5ff0
