kustomize:
  images:
  - europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts=europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts:663bed1585e6424b792dd954bdc7cff1d8e9ee3b
