apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-accounts
  template:
    metadata:
      labels:
        app: mako-accounts
        tier: backend
    spec:
      containers:
        - name: mako-accounts
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"        # Reduced from 128Mi
              cpu: "25m"            # Reduced from 50m
              ephemeral-storage: "100Mi"  # Reduced from 200Mi
            limits:
              memory: "128Mi"       # Reduced from 256Mi
              cpu: "100m"           # Reduced from 200m
              ephemeral-storage: "200Mi"  # Reduced from 500Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.argocd.svc.cluster.local:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudsql-proxy.argocd.svc.cluster.local:5432/mako_bank?currentSchema=accounts"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.argocd.svc.cluster.local:9092"
