apiVersion: apps/v1
kind: Deployment
metadata:
  name: mako-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mako-accounts
  template:
    metadata:
      labels:
        app: mako-accounts
    spec:
      containers:
        - name: mako-accounts
          image: "europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts:placeholder"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gke"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://mako-service-registry.mako-services.svc.cluster.local:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://cloudsql-proxy.mako-db.svc.cluster.local:5432/mako_bank?currentSchema=accounts"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
