apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts
  newName: europe-central2-docker.pkg.dev/mako-bank/mako-images/mako-accounts
  newTag: placeholder
